server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**