version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-car-service
    environment:
      POSTGRES_DB: car-service-db
      POSTGRES_USER: NGNFF
      POSTGRES_PASSWORD: 198273
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car-service-db
      SPRING_DATASOURCE_USERNAME: NGNFF
      SPRING_DATASOURCE_PASSWORD: 198273
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge